country=EU
update_config=1
ctrl_interface=/var/run/wpa_supplicant

# Connect to open network
network={
    ssid="GL-MT3000-947"
    key_mgmt=NONE
}

# Connect using WPA2
network={
	ssid="GL-MT3000-947"
	psk="Raspberry5aa"
	key_mgmt=WPA-PSK
}

# Connect using SAE
network={
    ssid="GL-MT3000-947"
    # WPA3-Personal uses SAE (Simultaneous Authentication of Equals)
    key_mgmt=SAE
    # The password for WPA3
    sae_password="ERFMMNY4X2"
    # Management Frame Protection is REQUIRED for WPA3 (2 = mandatory)
    ieee80211w=2
    # Protocol is RSN (Robust Security Network)
    proto=RSN
    # Standard encryption for WPA3
    pairwise=CCMP
    group=CCMP
}
